### ISSUE TITLE
Displaying markdown in frontmatter as HTML

### ISSUE THREAD

**Issue by freshyill** [gridsome/gridsome#1024]
Sorry if this is the wrong place to ask, but the Discord is dead and Stack Overflow had nothing. Googling only turns up false positives.

I have a simple question: How do I display frontmatter markdown as HTML? My frontmatter looks like this:

```yaml
title: whatever
sidebar: >-
  Here's some **markdown** in this field.

  I also have the youtube plugin installed `youtube:https://www.youtube.com/embed/dQw4w9WgXcQ`
```
This spits out markdown: 

`<div v-html="$page.page.sidebar" />`

This also spits out markdown: 

`<div>{{ $page.page.sidebar }}</div>`

I installed [vue-directive-markdown](vue-directive-markdown), and I can get it working, but it renders on the client side after a delay, and doesn't support the remark plugins. Also, with no updates in three years and six downloads a week, it doesn't seem like a great solution.

So am I doing something completely wrong, or misunderstanding something, or what? Thanks.
