### ISSUE TITLE
Broken Graphql from "Gridsome Netlify CMS Guide"

### ISSUE THREAD

**Issue by nttdataxd** [gridsome/gridsome#1119]
## Description

If you follow the documentation for getting started with Graphql you get half an example that you can't actually use.

If you follow them to set up a "Posts" collection in your Netlify config.yml
(Snippet)
```
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
```

create a post, and then you go to your GraphQL playground and try to query "allPost" following the docs (https://gridsome.org/docs/querying-data/) "title" is not recognized as a field under post but for some reason "belongsTo" is. If you try to query for "title" you will get the error "Cannot query field 'title' on type 'Post'".

I have no idea where "belongsTo" came from or how to fix it. Is this a Netlify bug or a Gridsome issue?

### Steps to reproduce

Follow the docs for  "Gridsome Netlify CMS Guide" https://gridsome.org/docs/guide-netlify-cms/#gridsome-netlify-cms-guide and then try to query for all posts following instructions from https://gridsome.org/docs/querying-data/
(Snippet)
```
query {
  allPost(sortBy: "title", order: DESC) {
    edges {
      node {
        title
      }
    }
  }
}
```

### Expected result

After creating a post and then querying for all posts I should be able to see the titles of all posts

### Actual result

Error message: "Cannot query field 'title' on type 'Post'".
