### ISSUE TITLE
Ability to query page_sections created in Forestry

### ISSUE THREAD

**Issue by Stafie** [gridsome/gridsome#1488]
## Description

This is probably not a bug, but more of a request for help as I've been trying to achieve it for the past two days without much hope. I am using Gridsome as the SSG for a marketing website, and is connected to Forestry from where I am creating/editing the pages. Each page is composed out of multiple components, that can differ (each component can contain different fields). For example, a page could be composed of: HeaderBlock, HeroBlock, RowBlock, TestimonialBlock, RowBlock, FaqBlock, etc. I have the data structure defined in forestry and it outputs .md files with front matter data when creating a page. An example of how the frontmatter for a page looks like is:

```
---
title: index
description: A clear and direct guide to writing
image_position: left
page_sections:
- template: hsds-row
  image_position: right
  title: You’re in control
  paragraph_text: <p class="hsds-row__p">Hubstaff works like a traditional time clock
    system that’s installed on a desktop or mobile device.</p>
  title_eyebrow: Principle 1
  image: "/uploads/app-control-panel-desktop-2x-35c6642512080b31c5ef28932c741476b80af4231467df34de0354a00da9e211.gif"
- template: hsds-faq
  title: Frequently asked questions
  faqs:
  - question: How do I know when screenshots are taken?
    answer: You’ll get alerts as screenshots are captured.
  - question: Does Hubstaff take webcam photos?
    answer: No. And we would never do this. We’re only concerned with capturing the
      work being done on the device.
- template: hsds-row
  image_position: left
  title_eyebrow: Principle 2
  title: Access to all your own information
  paragraph_text: "<p>You have access to your own data and can see exactly what management
    sees. </p>"
  image: "/uploads/access-to-data-desktop-2x.png"
---
```

### Steps to reproduce

In my Vue page template file, I'm query-ing the data and want to query all the page_section blocks, with the corresponding fields for each. My first guess was to do:

```
<page-query>
query ($path:String!) {
  hsdsPage(path: $path) {
    title
    description
    page_sections
  }
}
</page-query>
```
But unfortunately it doesn't let me to do it, as with GraphQL, I need to explicitly define each field from the page_section that I want to query. The problem is that not all items in the page_sections have the same fields, so I would end with pulled entries that would have a lot of unnecessary blank fields.

### Expected result

I would expect a way to query all the blocks with its corresponding fields. I am somehow sure that I am missing something as in Forestry documentation I have found examples that does exactly this for Hugo and Jekyll (but I cannot see how exactly they are pulling the data): https://forestry.io/docs/settings/fields/blocks/#hugo

### Actual result

When I try to query the page_sections without indicating each field, I get a `Field "page_sections" of type "[HsdsPage_PageSections]" must have a selection of subfields. Did you mean "page_sections { ... }"?"` error

### Environment

```
  npmPackages:
    @gridsome/plugin-sitemap: ^0.4.0 => 0.4.0
    @gridsome/source-filesystem: ^0.6.2 => 0.6.2
    @gridsome/transformer-remark: ^0.6.4 => 0.6.4
    gridsome: ^0.7.0 => 0.7.23
  npmGlobalPackages:
    @gridsome/cli: 0.3.4
```
