### ISSUE TITLE
CSS split configuration does not work

### ISSUE THREAD

**Issue by ThomOrlo** [gridsome/gridsome#265]
## Description

CSS split configuration does not work as expected.

### Steps to reproduce

1. create new project with default starter

```sh
> gridsome new my-website
```

2. enable CSS code-splitting : ``gridsome.config.js``

```js
module.exports = {
  css: {
    split: true
  }
};
```

3. generate site

```sh
> gridsome build
```

4. list generated files

```sh
> ls dist/assets/css/
```

### Expected result

<details><summary>0.styles.992f4026.css (layouts/Default.vue)</summary>

```css
body{font-family:-apple-system,system-ui,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;margin:0;padding:0;line-height:1.5}.layout{max-width:760px;margin:0 auto;padding-left:20px;padding-right:20px}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;height:80px}.nav__link{margin-left:20px}
```
</details>

<details><summary>3.styles.c6f58f08.css (pages/Index.vue)</summary>

```css
.home-links a{margin-right:1rem}
```
</details>

### Actual result

<details><summary>0.styles.992f4026.css</summary>

```css
body{font-family:-apple-system,system-ui,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif;margin:0;padding:0;line-height:1.5}.layout{max-width:760px;margin:0 auto;padding-left:20px;padding-right:20px}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;height:80px}.nav__link{margin-left:20px}.home-links a{margin-right:1rem}
```
</details>

---

#230
