### ISSUE TITLE
Static stylesheets overrides local component css

### ISSUE THREAD

**Issue by awulkan** [gridsome/gridsome#276]
## Description

Static stylesheets added in main.js overrides component css due to being placed further down in the <head>.

### Steps to reproduce

1. Add a static css file to your `static` folder.
2. Append it to the head.

```css
export default function (Vue, {router, head, isClient}) {
  head.link.push({
    rel: 'stylesheet',
    href: './my-static-styles.css'
  })
}
```
3. Add classes from the static css file in a component and try to override them with local css.
4. Run gridsome develop

### Expected result

Component css overrides static css.

### Actual result

Static css overrides component css.

### Environment
Libs:
- gridsome version: 0.5.5
- @gridsome/cli version: 0.0.8

Browser:
- [ X] Chrome (desktop) version 72.0.3626.121
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v11.10.0
- Platform:  Windows 10
