### ISSUE TITLE
Netlify CMS list not returned

### ISSUE THREAD

**Issue by mnlmaier** [gridsome/gridsome#450]
Hey guys,

I'm new to the JAMStack and can't figure out for the life of me how I'm able to properly query Lists of elements stored in Netlify CMS. Maybe this is a stupid question but as of now I'm totally lost.

I have several Services which each contain dynamic content pages.

```
collections:
  - name: "leistungen" # Used in routes, e.g., /admin/collections/blog
    label: "Leistungen" # Used in the UI
    folder: "leistungen" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Content"
        name: "content"
        widget: "list"
        types:
          - label: "Text"
            name: "text"
            widget: "objects"
            fields:
              - label: "Text"
                name: "text"
                widget: "markdown"
          - label: "Gallery"
            name: "gallery"
            widget: "object"
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                types:
                  - label: "Image"
                    name: "Image"
                    widget: "object"
                    fields:
                      - {label: "Image", name: "image", widget: "image"}
```

This is my `config.yml` and it's all showing up correctly on Netlify. Also when storing content, it all seems to be fine. Looking at my generated markdown files:

```
content:
  - images:
      - image: /images/uploads/00.jpg
        title: Title Image 0
        type: Image
      - image: /images/uploads/01.jpg
        title: Title Image 01
        type: Image
      - image: /images/uploads/02.png
        title: Title Image 02
        type: Image
```

But when I'm querying content, I'm always just getting `"content": "\n"` back.

Query in Explorer:
```
{
  allService {
    edges {
      node {
        title
        intro
        content
    	}
    }
  }
}
```

Other values like title, which are not in the list, return totally fine.

Am I wrong here or is this maybe an issue with the markup parser? I'm using `@gridsome/source-filesystem` for that.

Thanks in advance guys for any help, great project! I love it!
