### ISSUE TITLE
More Markdown extensions

### ISSUE THREAD

**Issue by tomtev** [gridsome/gridsome#61]
Could we add more markdown extensions to the remark transformer plugin?

VuePress has some nice ones:
https://vuepress.vuejs.org/guide/markdown.html

Thinking about these two:
- Table of contents `[[toc]]`
- Custom containers `::: tip :::` etc.

**Comment by mittalyashu** [comment]
Add the option for codegroup too.

![2018-10-16_21-10-57](https://user-images.githubusercontent.com/29014463/49666632-b5ef9200-fa7e-11e8-9fd0-b40e978bbceb.gif)

**Comment by IssuehuntBot** [comment]
@issuehuntfest has funded $20.00 to this issue. [See it on IssueHunt](https://issuehunt.io/repos/143078055/issues/61)

**Comment by EldoranDev** [comment]
Would you want to have the exact same functonality as the vuepress plugins or something similar ?

VuePress ist using markdown-it so the plugins they use can not get used i guess.

If you would want to have the same functionality the [toc-plugin](https://github.com/remarkjs/remark-toc) of remark would not quite fit so we would need to work arount that by using mdast-util-toc directly ?

Same for the cuustom blocks, there is a [plugin](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-custom-blocks) but its not quite the same as the markdown-it one.

**Comment by chadananda** [comment]
There is a nice list of Remark plugins here: https://github.com/remarkjs/remark/blob/master/doc/plugins.md#list-of-plugins

How would one go about converting these into Gridsome transformers or plugins?

**Comment by hjvedvik** [comment]
@chadananda Any Remark plugin should work with the Gridsome Remark transformer :)

**Comment by Jiang-Li** [comment]
I followed the instruction of Remark transformer, and added the `remark-toc`. But it doesn't work. Did anyone apply this before? 

The `remark-html-katex` works, but I need to add `import 'katex/dist/katex.min.css'` in the script tag. I am wondering do I need a css for toc? If so, where is it? Thx!

**Comment by Dana94** [comment]
@Jiang-Li `remark-toc` worked for me.

After running `npm install remark-toc`, I added it to the plugins list.
```js
remark: {
  plugins: [
    [ 'gridsome-plugin-remark-shiki', { theme: 'Material-Theme-Palenight', skipInline: true } ],
    'remark-toc'
  ]
 }
```
Then added this line to the top of my markdown file and it works.

`## Table of Contents`

**Comment by danrocha** [comment]
Trying to use `remark-toc` with `@gridsome/vue-remark` plugin and could not make it work:

```js
    {
      use: '@gridsome/vue-remark',
      options: {
        typeName: 'Guide', // Required
        baseDir: './content/guides', // Where .md files are located
        pathPrefix: '/guides', // Add route prefix. Optional
        template: './src/templates/Guide.vue',
        plugins: ['remark-toc'],
      },
    },
```
In my markdown, added `## toc` or `## Table of Contents` as per [instructions](https://github.com/remarkjs/remark-toc) and they are ignored.

Has anyone else managed to make it work?

**Comment by noxify** [comment]
Hi @danrocha ,

My package is a bit outdated but the `remark-toc` plugin works fine for me.

My content repository: 
https://github.com/noxify/gridsome-content-test

My Gridsome repository:
https://github.com/noxify/gridsome-preview

Preview:
https://gridsome-preview.ilovenox.now.sh/gitpost/c86b33a3520cbe232519ea0971fdbb5e

Hope that helps :)

**Comment by danrocha** [comment]
Hi @noxify thanks for the help...
however, I believe it might be an issue with `@gridsome/vue-remark` (see #707 )

will keep trying....

**Comment by cypressious** [comment]
Has anyone got https://github.com/Nevenall/remark-containers working? I couldn't get it to work with or without `vue-remark.`

**Comment by RehanSaeed** [comment]
I figured out how to do TOC and custom containers. This should ideally be built in. Here is my `gridsome.config.js`:

```js
plugins: [
        [
          'remark-containers',
          {
            default: false,
            custom: [
              {
                type: 'tip',
                element: 'div',
                transform: function(node, config, tokenize) {
                  return transformContainer(node, config, 'tip', 'p', "Tip");
                }
              },
              {
                type: 'warning',
                element: 'div',
                transform: function(node, config, tokenize) {
                  return transformContainer(node, config, 'warning', 'p', "Warning");
                }
              },
              {
                type: 'danger',
                element: 'div',
                transform: function(node, config, tokenize) {
                  return transformContainer(node, config, 'danger', 'p', "Warning");
                }
              },
              {
                type: 'details',
                element: 'details',
                transform: function(node, config, tokenize) {
                  return transformContainer(node, config, 'details', 'summary', "Details");
                }
              }
            ]
          }
        ],
        'remark-toc'
]

function transformContainer(node, config, type, element, defaultTitle) {
  node.data.hProperties = {
    className: `custom-block ${type}`
  };
  node.children.splice(0, 0, {
    type: 'paragraph',
    data: {
      hName: element,
      hProperties: {
        className: 'custom-block-title',
      },
    },
    children: [
      { type: 'text', value: config || defaultTitle }
    ]
  });
}
```

The sass for the containers which I adjusted:

```scss
.custom-block {
  margin: 0.8rem 0;

  .custom-block-title {
    font-weight: 600;
    line-height: 1.7;
  }

  p {
    margin-bottom: 0;
  }

  &.tip, &.warning, &.danger {
    padding: 1rem 1.4rem;
    border-left-width: .4rem;
    border-left-style: solid;
    margin-bottom: -0.32rem;
  }

  &.tip {
    background-color: #f3f5f7;
    border-color: #42b983;
  }

  &.warning {
    background-color: rgba(255,229,100,.3);
    border-color: darken(#ffe564, 35%);
    color: darken(#ffe564, 70%);

    .custom-block-title {
      color: darken(#ffe564, 50%);
    }
  }

  &.danger {
    background-color: #ffe6e6;
    border-color: darken(red, 20%);
    color: darken(red, 70%);

    .custom-block-title {
      color: darken(red, 40%);
    }
  }

  &.details {
    background-color: #eee;
    display: block;
    padding: 1rem 1.4rem;
    position: relative;

    summary {
      cursor: pointer;
      font-size: 1.2em;
      outline: none;
    }
  }

}
```
