### ISSUE TITLE
Use bootstrap-vue  bootstrap

### ISSUE THREAD

**Issue by xhostcom** [gridsome/gridsome#632]
## Summary
Just want to use the bootstrap-vue npm module and bootsrap (scss), their docs instruct for Vue CLI, so slightly different here.
Currently I've got them registered in index.js with code below
module.exports = {
  plugins: [
    {
      use: '~/node_modules/bootstrap/scss/bootstrap',
      options: {}
    },
    {
      use: '~/node_modules/bootstrap-vue/src/index.scss',
      options: {}
    }
 
  ]
}

which appear fine, I am guessing (I know not supposed to guess) that we don't need the Vue use command.
So now want to import the respective scss files in to main,js, and have got so far 
import '~/node_modules/bootstrap/scss/bootstrap';
 which is not working, what is the correct way to import these scss files from node modules in to main.js? Thanks
### Basic example

Examples above.

### Motivation
Get bootstrap-vue and bootstrap with scss working in Gridsome, for quicker bootstrap starter projects.

**Comment by xhostcom** [comment]
Hi, I got all this working, but on build have an error with the /dist/bootstrap -vue.css firl rom Node Modules, whilst this works in dev, on build get at error with the @charset as below 
Failed to render /about
/home/anton/VueProjects/vuewp-gridsome-scss-bootstrap-avivo/node_modules/bootstrap-vue/dist/bootstrap-vue.css:1                                           
@charset "UTF-8";
^
Its the same if remove about.vue, says the same for the next link/file

Any idea why? Thanks

**Comment by derevandal** [comment]
I'm using bootstrap-vue with gridsome.
This is my setup:
`src/main.js`
```js
import VueDisqus from 'vue-disqus'

import DefaultLayout from '~/layouts/Default.vue'

import Bootstrap from 'bootstrap-vue'

import '~/assets/scss/app.scss'

export default function(Vue, { router, head, isClient }) {
  // Set default layout as a global component
  Vue.use(Bootstrap)
  Vue.use(VueDisqus)
  Vue.component('Layout', DefaultLayout)
  head.script.push({
    src: 'https://identity.netlify.com/v1/netlify-identity-widget.js',
    body: true,
    async: true
  })
}
```
`src/assets/scss/app.scss`
``` scss
$theme-colors: (
  'primary': #1fde91,
  'secondary': #083ea7,
  'dark': #1a202c,
  'black': #000000
);

$grid-breakpoints: (
  xs: 0,
  sm: 480px,
  md: 640px,
  lg: 992px,
  xl: 1300px
);

$btn-border-radius: 999999px;
$btn-border-radius-sm: 999999px;
$btn-border-radius-lg: 999999px;

html {
  scroll-behavior: smooth;
}

// Then include the following
@import 'bootstrap/scss/bootstrap.scss';
@import 'bootstrap-vue/src/index.scss';
```
And it working :D
