### ISSUE TITLE
Live reload doesn't work on @import scss files from other scss files

### ISSUE THREAD

**Issue by SimonMckeon** [gridsome/gridsome#71]
## Description

When using a main scss file to @import other scss files, live reload only works when saving the parent file. 

### Steps to reproduce

1. Create "main.scss"
2. Create "_other.scss"
3. @import "_other.scss" in "main.scss"
4. Run "gridsome develop"
5. Change code in "_other.scss"
6. Live reload doesn't notice the change and trigger

### Expected result

Live reload should be triggered by changing and saving "_other.scss"

### Actual result

Live reload isn't triggered unless parent scss file "main.scss" is saved

**Comment by Devportobello** [comment]
Cannot reproduce this error on Gridsome v0.3.6

`main.js`
```js
import '~/assets/styles.scss'
```
`styles.scss`
```scss
@import "_test.scss";
a {
  color: red;
}
```
`_test.scss`
```scss
a {
  text-decoration: underline;
}
```
`gridsome develop` then editing `_test.scss` i can see hot reloading
