### ISSUE TITLE
Deploying Gridsome projects on shared hosting

### ISSUE THREAD

**Issue by cobbie** [gridsome/gridsome#910]
Hello, is it possible to put up a Gridsome site using a shared hosting service, such as on Bluehost? My understanding is that you could just run `gridsome build` locally and upload `dist` to the web root, such as how it's done in [Gatsby](https://github.com/gatsbyjs/gatsby/issues/1555). But when I tried doing so, only the plain HTML rendered (no CSS or JS). Is there anything missing with the process?

Thanks!

**Comment by noxify** [comment]
I had the same challenge.

In my case, my hoster has Plesk as Web Interface, which supports  adding a remote git repo.
( https://docs.plesk.com/en-US/obsidian/customer-guide/git-support/using-remote-git-hosting.75848/ )

With this, I was able to build my site via a GIthub Workflow.
The builded site will be pushed to a private git repo which is connected with the Plesk Interface.

If your hoster as not Plesk as Web Interface or has disabled the git functionality you can alternative use a FTP Deploy Action to deploy your site.

Here are some FTP actions:
https://github.com/marketplace?utf8=%E2%9C%93&type=actions&query=ftp

Here the used workflow action which builds the site and updates the private repo.
(you can easily replace the Deploy step with the ftp action)

```
on: 
  push:
    branches: 
      - master
name: Build and Publish Website
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build
      run: |
        npm install
        npm run build --if-present
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: noxify/itsmplus-build
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
```
